### PR TITLE
add harvester-journal chart

### PR DESCRIPTION
**Pull request by joshmeranda**
Problem:
We needed to be able to collect harvester cluster host system logs.

Solution:
Install a modified version of the rancher [journal-aggregator](https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-logging/3.17.700%2Bup3.17.7/templates/loggings/rke2/daemonset.yaml/) `daemonset`.

Related Issue:
https://github.com/harvester/harvester/issues/577
https://github.com/harvester/harvester/issues/2647

Test plan:

cc @guangbochen @bk201 @w13915984028

### CODE REVIEW

**Comment by bk201** [comment]
@joshmeranda Please help fix the CI error. Thanks!

**Review by guangbochen — COMMENTED** [review]
Can you specify what has been modified agaisnt the upstream rancher [journal-aggregator](https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-logging/3.17.700%2Bup3.17.7/templates/loggings/rke2/daemonset.yaml/) (using commit to track changes would be preferred), additionally Harvester uses rke2 under-the-hood, so can we use the upstream chart directly and add missing values if needed? thanks. cc @w13915984028

**Comment by w13915984028** [comment]
@guangbochen   Here is the difference. (left: @joshmeranda 's commit;  right: `rancher-logging` `rke2`)
image

I will check with @joshmeranda , if wen can reuse `rancher-logging`.

**Comment by joshmeranda** [comment]
@guangbochen @w13915984028 The difference is that `journald-aggregator` only collects rke2 logs from the journal, but `harvester-journal` collects everything as of now. In harvester issue [577](https://github.com/harvester/harvester/issues/577) one of the requirements was collecting "Log in the OS. E.g. major system logs under /var/log/". `journald-aggregator` is too specific.

We could add a new [logging source](https://github.com/rancher/charts/tree/dev-v2.7/charts/rancher-logging/3.17.700%2Bup3.17.7/templates/loggings) to `rancher-logging`, and  just enable it under `additionalLoggingSources`. One thing to note about that solution, is that the `rke` and `rke2` logging sources will have some overlap, so we'll probably want to add some additional logic to disable those sources if the `harvester-journal` logging source is enabled.

**Comment by bk201** [comment]
@joshmeranda @w13915984028 Per the discussion, including everything under `/var/log` might be too much. Here are logs we feel helpful to collect:
- /var/log/audit/audit.log
- Kernel log: `journalctl -k` output. (We use journald to store it by default).
- Log of these systemd services: `rke2-server rke2-agent rancherd rancher-system-agent wicked iscsid`
- `/var/lib/rancher/rke2/agent/logs/kubelet.log`

**Comment by joshmeranda** [comment]
@guangbochen @bk201 
Sounds like that would still be more logs than what the rancher logging `journal-aggregator` collects. We could add more `additionalLoggingSources` to rancher-logging if we can wait for the next rancher release before those logging sources are available to harvester.

**Comment by w13915984028** [comment]
This PR is replaced by https://github.com/harvester/harvester-installer/pull/333, close.

**Pull request closed without merging**
