### PR TITLE
charts: bump harvester-node-disk-manager to v0.5.0

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
- follow the latest NDM release

### CODE REVIEW

**Comment by guangbochen** [comment]
can we split the commit and backport the template and CRD files to the master first, thanks.

**Comment by Vicente-Cheng** [comment]
> can we split the commit and backport the template and CRD files to the master first, thanks.

Sure, open the PR (https://github.com/harvester/charts/pull/187) to master

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Review by chrisho — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
