### PR TITLE
Remove use of deprecated label

### PR DESCRIPTION
**Pull request by connorkuehl**
Before:

	$ helm package .
	Successfully packaged chart and saved it to: /.../charts/charts/harvester-network-controller/harvester-network-controller-0.3.2.tgz

	$ helm upgrade --dry-run -n harvester-system harvester harvester-network-controller-0.3.2.tgz | grep beta\.kubernetes\.io\/os | wc -l
	1

After:

	$ helm package .
	Successfully packaged chart and saved it to: /.../charts/charts/harvester-network-controller/harvester-network-controller-0.3.2.tgz

	$ helm upgrade --dry-run -n harvester-system harvester harvester-network-controller-0.3.2.tgz | grep beta\.kubernetes\.io\/os | wc -l
	0

Related-to: https://github.com/harvester/harvester/issues/2899

### CODE REVIEW

**Review by guangbochen — APPROVED** [review]
LGTM, thanks. cc @yaocw2020 please help to remove this from the manifest example on the network-controller side.

**Review by futuretea — APPROVED** [review]
LGTM, Thanks

**Comment by yaocw2020** [comment]
> LGTM, thanks. cc @yaocw2020 please help to remove this from the manifest example on the network-controller side.

Prefer to remove the manifest example because it's outdated.

**Review by yaocw2020 — APPROVED** [review]
LGTM, thanks

**Comment by connorkuehl** [comment]
Whose responsibility is it to merge this? GitHub is giving me the option to rebase & merge. Do I do it? Or do I wait for maintainers to merge after approval?

CC: @guangbochen @bk201 @futuretea

**Comment by guangbochen** [comment]
Usually the last reviewer will merge it, @bk201 can u PTAL when u have time, thanks.

**Review by bk201 — APPROVED** [review]

**Pull request merged**
