### PR TITLE
chore: bump vm-dhcp-controller to 0.3.2

### PR DESCRIPTION
**Pull request by starbops**
Bump harvester-vm-dhcp-controller

- chart version: 0.3.2
- app version: v0.3.2

### CODE REVIEW

**Comment by Yu-Jack** [comment]
I'm thinking if we re-tag v0.3.2 in vm-dhcp-controller, the the app and chart version could be consistent. What do you think?

**Comment by starbops** [comment]
@Yu-Jack Retagged and updated the PR. PTAL, thank you!

**Review by bk201 — APPROVED** [review]

**Review by Yu-Jack — APPROVED** [review]
LGTM, thanks!

**Comment by starbops** [comment]
I'm checking the CI issue https://github.com/harvester/vm-dhcp-controller/actions/runs/11495119631/job/31994935507
Please do not merge this PR yet.

**Pull request merged**
