### PR TITLE
charts: update volume related configuration and rbac

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
- with the latest node-manager changes, we also need to update here
    - also add new CRD nodeconfigs

Signed-off-by: Vicente Cheng <vicente.cheng@suse.com>
(cherry picked from commit 19c250302b3932c1be8e3b491d978bac1f9565c6)

### CODE REVIEW

**Comment by bk201** [comment]
Need to bump chart version and image version.

**Comment by Vicente-Cheng** [comment]
> Need to bump chart version and image version.

Updated!

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Review by bk201 — APPROVED** [review]
LGTM, thanks

**Pull request merged**
