### PR TITLE
charts: update volume related configuration and rbac

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
- with the latest node-manager changes, we also need to update here

That changes should be merged after https://github.com/harvester/node-manager/pull/10

### CODE REVIEW

**Comment by bk201** [comment]
Better to start from `master` branch and backport to the `release` one, and we need to bump version in the release branch.

**Comment by Vicente-Cheng** [comment]
> Better to start from `master` branch and backport to the `release` one, and we need to bump version in the release branch.

Thanks for the reminder! Updated!

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Review by bk201 — APPROVED** [review]
LGTM, please merge and backport once NTP-related PRs are merged.

**Comment by Vicente-Cheng** [comment]
> Need to include the CRD file https://github.com/harvester/node-manager/pull/10/files#diff-5270618f5e98c90c08716eeeb09acb482045eeeaaf2021fccdcea5b24f6b5479

Updated! Thanks for the reminder

**Review by bk201 — APPROVED** [review]
Thanks!

**Pull request merged**
